/*
** Generator for precomputed Unicode fold tables.
**
** Compile:
**   MSVC: cl -I deps/sqlite-src-3530400/ext/fts5 gen-fold-table.c
**   GCC:  gcc -I deps/sqlite-src-3530400/ext/fts5 -o gen-fold-table gen-fold-table.c
**
** Run: gen-fold-table.exe
**
** Produces:
**   fold-table.h           - aFoldTable[65536] (case fold only)
**   fold-diacritic-table.h - aFoldDiacriticTable[65536] (fold + diacritic removal)
*/

#include <stdio.h>
#include <stdint.h>
#include <assert.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>

/* fts5_unicode2.c needs u8/u16/u32 typedefs (normally from fts5Int.h) */
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;

#include "fts5_unicode2.c"

static void generate_table(const char *zFilename, const char *zGuard,
                           const char *zArrayName, int eRemoveDiacritic) {
  FILE *f = fopen(zFilename, "w");
  if (!f) {
    perror(zFilename);
    return;
  }

  fprintf(f, "/* Auto-generated by gen-fold-table.c. Do not edit. */\n");
  fprintf(f, "#ifndef %s\n#define %s\n\n", zGuard, zGuard);
  fprintf(f, "#include <stdint.h>\n\n");
  fprintf(f, "static const uint16_t %s[65536] = {\n", zArrayName);

  for (int c = 0; c < 65536; c++) {
    int folded = sqlite3Fts5UnicodeFold(c, eRemoveDiacritic);
    fprintf(f, "  %4d", folded);
    if (c < 65535)
      fprintf(f, ",");
    if ((c + 1) % 8 == 0)
      fprintf(f, "\n");
    else
      fprintf(f, "  ");
  }

  fprintf(f, "};\n\n#endif /* %s */\n", zGuard);
  fclose(f);
  printf("Generated %s\n", zFilename);
}

int main(void) {
  generate_table("fold-table.h", "FOLD_TABLE_H", "aFoldTable", 0);
  generate_table("fold-diacritic-table.h", "FOLD_DIACRITIC_TABLE_H",
                 "aFoldDiacriticTable", 2);
  return 0;
}
